### ISSUE TITLE
Warnings !

### ISSUE THREAD

**Issue by jdmedeiros** [JackpotClavin/Android-Blob-Utility#1]
First of all, thanks for this great utility. Second, can you tell me how important are warnings such as "warning: blob file libcamera_f.so missing or broken" and how would I go about resolving these warnings?

Thanks!

**Comment by JackpotClavin** [comment]
It means that there is a library looking around for a library called libcamera_f.so.

This libcamera_f.so may be obsolete and never removed from the code of the library that wants it, or it may be that libcamera_f.so actually exists in your /system dump, but it is not in one of the 8 directories looked in by the blob utility. Do a search of your /system dump for a libcamera_f.so and let me know if it's there, and where its location is.

Chances are it's just an obsolete library never removed from code, so the blob utility will complain that it's not there, but it isn't a problem if it isn't in your stock /system dump, so you can ignore it.

**Comment by jdmedeiros** [comment]
It's not there; thanks very much for your answer.
